blank_issues_enabled: false
contact_links:
  - name: Official Discord Server
    url: https://discord.trackverse.com
    about: If you are experiencing issues with your TrackVerse, go to our support in our Discord server.
