services:
  postgres:
    container_name: trackverse-postgres
    image: postgres:13
    restart: always
    ports:
      - '20141:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trackverse
    volumes:
      - ./postgres:/var/lib/postgresql/data