name: Crowdin Sync
permissions: write-all
  
on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  crowdin-sync:
    name: Crowdin Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload sources
        uses: crowdin/github-action@v2
        with:
          upload_sources: true 
          upload_translations: false
          download_translations: true
          github_user_name: "github-actions[bot]"
          github_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          localization_branch_name: "feat/crowdin-sync"
          create_pull_request: true
          pull_request_title: "chore(i18n): update translations"
          pull_request_body: "Translations synced from Crowdin"
        env:
          GITHUB_TOKEN: ${{ secrets.GHT }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}